/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.televisionInventoryMS.view;

import com.televisionInventoryMS.model.inventoryMS;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.televisionInventoryMS.controller.algorithm.selectionSort;
import com.televisionInventoryMS.controller.algorithm.insertionSort;
import com.televisionInventoryMS.controller.algorithm.mergeSort;
import com.televisionInventoryMS.controller.algorithm.selectionSortCompany;
import com.televisionInventoryMS.controller.algorithm.binarySearch;
import java.util.ArrayList;
/**
 *
 * @author pratikmanpradhan
 */
public class Inventory extends javax.swing.JFrame {
    
    private List<inventoryMS> productList;
    private java.awt.CardLayout cardLayout;
    private selectionSort selectionsort;
    private insertionSort insertionsort;
    private mergeSort mergesort;
    private selectionSortCompany selectionsortcompany;
    private binarySearch binarysearch;

    public Inventory() {
    // Initialize the UI and layout
    productList = new LinkedList<>();
    initComponents(); // Initialize components like buttons, labels, text fields, etc.
    initializeLayout();
    loadScreen("LoginScreen");// Set up the CardLayout and panels
    loadProductInitialData();
}

    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPnl = new javax.swing.JPanel();
        headerLogo = new javax.swing.JLabel();
        headerCompanyName = new javax.swing.JLabel();
        headerCompanySlogan = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        bodyPnl = new javax.swing.JTabbedPane();
        homePnl = new javax.swing.JPanel();
        homeWlcMsgLbl = new javax.swing.JLabel();
        userGuideTitleLbl = new javax.swing.JLabel();
        userGuideScrollPnl = new javax.swing.JScrollPane();
        userGuideTxtArea = new javax.swing.JTextArea();
        inventoryStockPnl = new javax.swing.JPanel();
        searchLbl = new javax.swing.JLabel();
        searchTxtField = new javax.swing.JTextField();
        sortLbl = new javax.swing.JLabel();
        sortComboBox = new javax.swing.JComboBox<>();
        inventoryTableScrollPnl = new javax.swing.JScrollPane();
        inventoryTbl = new javax.swing.JTable();
        sortButton = new javax.swing.JButton();
        refershButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        manageInventoryPnl = new javax.swing.JPanel();
        modelNoTxtFld = new javax.swing.JTextField();
        sizeTxtFld = new javax.swing.JTextField();
        priceTxtFld = new javax.swing.JTextField();
        resolutionTxtFld = new javax.swing.JTextField();
        inStockTxtFld = new javax.swing.JTextField();
        companyTxtFld = new javax.swing.JTextField();
        smartCheckBox = new javax.swing.JCheckBox();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        supportPnl = new javax.swing.JPanel();
        helpLbl = new javax.swing.JLabel();
        helpTxtFld = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        leftPnl = new javax.swing.JPanel();
        companyNameLbl = new javax.swing.JLabel();
        companySloganLbl = new javax.swing.JLabel();
        tvLbl = new javax.swing.JLabel();
        mgmtLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        copyrightLbl = new javax.swing.JLabel();
        rightPnl = new javax.swing.JPanel();
        welcomeLbl = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        usernameTxtFld = new javax.swing.JTextField();
        rememberMeCheckBox = new javax.swing.JCheckBox();
        forgotPasswordLbl = new javax.swing.JLabel();
        logInBtn = new javax.swing.JButton();
        loginErrorLbl = new javax.swing.JLabel();
        passwordTxtFld = new javax.swing.JPasswordField();

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setMaximumSize(new java.awt.Dimension(1450, 850));
        mainPanel.setMinimumSize(new java.awt.Dimension(1450, 850));
        mainPanel.setPreferredSize(new java.awt.Dimension(1450, 850));
        mainPanel.setSize(new java.awt.Dimension(1450, 850));

        headerPnl.setBackground(new java.awt.Color(204, 204, 204));
        headerPnl.setMaximumSize(new java.awt.Dimension(1450, 100));
        headerPnl.setMinimumSize(new java.awt.Dimension(1450, 100));
        headerPnl.setPreferredSize(new java.awt.Dimension(1450, 100));

        headerLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/televisionInventoryMS/resources/mainpagelogo.png"))); // NOI18N

        headerCompanyName.setFont(new java.awt.Font("Helvetica Neue", 1, 95)); // NOI18N
        headerCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerCompanyName.setText("     हाम्रो कारखाना।");

        headerCompanySlogan.setFont(new java.awt.Font("Devanagari MT", 2, 14)); // NOI18N
        headerCompanySlogan.setText("With the vision to provide you finest electronic appliances.");
        headerCompanySlogan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        logOutBtn.setFont(new java.awt.Font("Damascus", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setAlignmentY(0.0F);
        logOutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPnlLayout = new javax.swing.GroupLayout(headerPnl);
        headerPnl.setLayout(headerPnlLayout);
        headerPnlLayout.setHorizontalGroup(
            headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPnlLayout.createSequentialGroup()
                .addComponent(headerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(headerCompanySlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPnlLayout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(headerCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(228, 228, 228)))
        );
        headerPnlLayout.setVerticalGroup(
            headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerCompanySlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(headerPnlLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(headerCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );

        bodyPnl.setBackground(new java.awt.Color(0, 0, 0));
        bodyPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bodyPnl.setForeground(new java.awt.Color(255, 255, 255));
        bodyPnl.setOpaque(true);

        homePnl.setBackground(new java.awt.Color(0, 0, 0));
        homePnl.setPreferredSize(new java.awt.Dimension(1450, 850));

        homeWlcMsgLbl.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 50)); // NOI18N
        homeWlcMsgLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeWlcMsgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeWlcMsgLbl.setText("Welcome to Television Inventory Management System");

        userGuideTitleLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        userGuideTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        userGuideTitleLbl.setText("USER GUIDE:");

        userGuideTxtArea.setEditable(false);
        userGuideTxtArea.setColumns(20);
        userGuideTxtArea.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        userGuideTxtArea.setRows(5);
        userGuideTxtArea.setText("\n       This is the \"Home\" page of this television Inventory management system. After logging into the application, admin can find various tabs \n       above. Each tabs has its own functionality. Functionality of different tabs are described in breif below:\n\n       1) Inventory Stock: In this tab, you can see the table listing all the products sorted in the order user wants them to sort. You can also find\n\t             the search bar to search the products and their status.\n\n       2) Manage Inventory: In this tab, you can manipulate product and their availability. You can find various text fields with their own purposes \n\t                  like company name, model no,etc. You can add product, update their information and status, remove product with the\n\t                  help of different buttons.\n\n       3) Support: In this tab, admin's problem related to the software will be assisted by the developer.\n\n       4) About Us: In this tab, you can find information about developers, this company and how they operate.\n");
        userGuideScrollPnl.setViewportView(userGuideTxtArea);

        javax.swing.GroupLayout homePnlLayout = new javax.swing.GroupLayout(homePnl);
        homePnl.setLayout(homePnlLayout);
        homePnlLayout.setHorizontalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeWlcMsgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userGuideTitleLbl)
                    .addComponent(userGuideScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        homePnlLayout.setVerticalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homeWlcMsgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userGuideTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userGuideScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        bodyPnl.addTab("Home", homePnl);

        inventoryStockPnl.setBackground(new java.awt.Color(0, 0, 0));
        inventoryStockPnl.setForeground(new java.awt.Color(255, 51, 51));

        searchLbl.setFont(new java.awt.Font("Devanagari MT", 1, 24)); // NOI18N
        searchLbl.setForeground(new java.awt.Color(255, 255, 255));
        searchLbl.setText("Search:");

        searchTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFieldActionPerformed(evt);
            }
        });

        sortLbl.setFont(new java.awt.Font("Devanagari MT", 1, 24)); // NOI18N
        sortLbl.setForeground(new java.awt.Color(255, 255, 255));
        sortLbl.setText("Sort by:");
        sortLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        sortComboBox.setBackground(new java.awt.Color(0, 0, 0));
        sortComboBox.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 14)); // NOI18N
        sortComboBox.setForeground(new java.awt.Color(255, 0, 0));
        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model No", "Size", "Price", "Company" }));
        sortComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortComboBoxActionPerformed(evt);
            }
        });

        inventoryTbl.setBackground(new java.awt.Color(0, 0, 0));
        inventoryTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        inventoryTbl.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 14)); // NOI18N
        inventoryTbl.setForeground(new java.awt.Color(255, 255, 255));
        inventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Model No", "Company", "Size", "Price", "Resolution", "Smart?", "In stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inventoryTbl.setShowGrid(true);
        inventoryTbl.getTableHeader().setReorderingAllowed(false);
        inventoryTableScrollPnl.setViewportView(inventoryTbl);
        if (inventoryTbl.getColumnModel().getColumnCount() > 0) {
            inventoryTbl.getColumnModel().getColumn(0).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(1).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(2).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(3).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(4).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(5).setResizable(false);
            inventoryTbl.getColumnModel().getColumn(6).setResizable(false);
        }

        sortButton.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 18)); // NOI18N
        sortButton.setText("Sort");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        refershButton.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 18)); // NOI18N
        refershButton.setText("Refresh");
        refershButton.setAlignmentY(0.0F);
        refershButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refershButtonActionPerformed(evt);
            }
        });

        searchButton1.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 18)); // NOI18N
        searchButton1.setText("Search");
        searchButton1.setAlignmentY(0.0F);
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventoryStockPnlLayout = new javax.swing.GroupLayout(inventoryStockPnl);
        inventoryStockPnl.setLayout(inventoryStockPnlLayout);
        inventoryStockPnlLayout.setHorizontalGroup(
            inventoryStockPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryStockPnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(searchLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inventoryStockPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inventoryStockPnlLayout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refershButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sortLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inventoryTableScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        inventoryStockPnlLayout.setVerticalGroup(
            inventoryStockPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryStockPnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(inventoryStockPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLbl)
                    .addComponent(sortLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortComboBox)
                    .addComponent(sortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refershButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(inventoryTableScrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        bodyPnl.addTab("Inventory Stock", inventoryStockPnl);

        manageInventoryPnl.setBackground(new java.awt.Color(0, 0, 0));

        modelNoTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        modelNoTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Model No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        modelNoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNoTxtFldActionPerformed(evt);
            }
        });

        sizeTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        sizeTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        sizeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTxtFldActionPerformed(evt);
            }
        });

        priceTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        priceTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        resolutionTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        resolutionTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resolution", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        inStockTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        inStockTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        inStockTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStockTxtFldActionPerformed(evt);
            }
        });

        companyTxtFld.setBackground(new java.awt.Color(153, 153, 153));
        companyTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Company", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        companyTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTxtFldActionPerformed(evt);
            }
        });

        smartCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        smartCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        smartCheckBox.setText("Smart?");

        updateBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateBtn.setText("Update Current Item ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(204, 204, 204));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addBtn.setText("Add New Item");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteBtn.setText("Delete Current Item");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(51, 51, 51));
        clearBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 0, 0));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageInventoryPnlLayout = new javax.swing.GroupLayout(manageInventoryPnl);
        manageInventoryPnl.setLayout(manageInventoryPnlLayout);
        manageInventoryPnlLayout.setHorizontalGroup(
            manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageInventoryPnlLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageInventoryPnlLayout.createSequentialGroup()
                        .addComponent(smartCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(manageInventoryPnlLayout.createSequentialGroup()
                        .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageInventoryPnlLayout.createSequentialGroup()
                                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(companyTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resolutionTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageInventoryPnlLayout.createSequentialGroup()
                                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(241, 241, 241)))
                        .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inStockTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn))
                        .addGap(90, 90, 90))))
        );
        manageInventoryPnlLayout.setVerticalGroup(
            manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageInventoryPnlLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resolutionTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inStockTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(smartCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(manageInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        bodyPnl.addTab("Manage Inventory", manageInventoryPnl);

        supportPnl.setBackground(new java.awt.Color(0, 0, 0));

        helpLbl.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        helpLbl.setForeground(new java.awt.Color(255, 255, 255));
        helpLbl.setText("How can I help?");

        helpTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout supportPnlLayout = new javax.swing.GroupLayout(supportPnl);
        supportPnl.setLayout(supportPnlLayout);
        supportPnlLayout.setHorizontalGroup(
            supportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportPnlLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(supportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpLbl))
                .addContainerGap(652, Short.MAX_VALUE))
        );
        supportPnlLayout.setVerticalGroup(
            supportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportPnlLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(helpLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );

        bodyPnl.addTab("Support", supportPnl);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(1450, 850));
        loginPanel.setLayout(null);

        leftPnl.setBackground(new java.awt.Color(255, 255, 255));
        leftPnl.setPreferredSize(new java.awt.Dimension(725, 850));

        companyNameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 80)); // NOI18N
        companyNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameLbl.setText(" हाम्रो कारखाना।");

        companySloganLbl.setFont(new java.awt.Font("Devanagari MT", 2, 18)); // NOI18N
        companySloganLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companySloganLbl.setText("            With the vision to provide you finest electronic appliances.");

        tvLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        tvLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvLbl.setText("Television Inventory");

        mgmtLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 50)); // NOI18N
        mgmtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mgmtLbl.setText("Management System");

        logoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/televisionInventoryMS/resources/final.png"))); // NOI18N
        logoLbl.setPreferredSize(new java.awt.Dimension(100, 100));

        copyrightLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        copyrightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLbl.setText("copyright © Islington College All rights reserved.");

        javax.swing.GroupLayout leftPnlLayout = new javax.swing.GroupLayout(leftPnl);
        leftPnl.setLayout(leftPnlLayout);
        leftPnlLayout.setHorizontalGroup(
            leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPnlLayout.createSequentialGroup()
                .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mgmtLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tvLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(companyNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                        .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyrightLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(companySloganLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPnlLayout.setVerticalGroup(
            leftPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPnlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(companyNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companySloganLbl)
                .addGap(44, 44, 44)
                .addComponent(tvLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mgmtLbl)
                .addGap(18, 18, 18)
                .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        loginPanel.add(leftPnl);
        leftPnl.setBounds(0, 0, 725, 910);

        rightPnl.setBackground(new java.awt.Color(0, 0, 0));
        rightPnl.setPreferredSize(new java.awt.Dimension(725, 850));
        rightPnl.setSize(new java.awt.Dimension(730, 850));

        welcomeLbl.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl.setText("WELCOME");

        loginLbl.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 18)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(204, 204, 204));
        loginLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLbl.setText("Login with Username");

        usernameTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        usernameTxtFld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFldActionPerformed(evt);
            }
        });

        rememberMeCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        rememberMeCheckBox.setText("Remember me");
        rememberMeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberMeCheckBoxActionPerformed(evt);
            }
        });

        forgotPasswordLbl.setForeground(new java.awt.Color(204, 204, 204));
        forgotPasswordLbl.setText("Forgot Password?");
        forgotPasswordLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLblMouseClicked(evt);
            }
        });

        logInBtn.setBackground(new java.awt.Color(204, 204, 204));
        logInBtn.setFont(new java.awt.Font("Devanagari Sangam MN", 1, 18)); // NOI18N
        logInBtn.setText("LOGIN");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        loginErrorLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginErrorLbl.setForeground(new java.awt.Color(255, 0, 0));
        loginErrorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginErrorLbl.setToolTipText("");

        passwordTxtFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        javax.swing.GroupLayout rightPnlLayout = new javax.swing.GroupLayout(rightPnl);
        rightPnl.setLayout(rightPnlLayout);
        rightPnlLayout.setHorizontalGroup(
            rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPnlLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(loginLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPnlLayout.createSequentialGroup()
                .addGap(0, 166, Short.MAX_VALUE)
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPnlLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(logInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(144, 144, 144))
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPnlLayout.createSequentialGroup()
                        .addComponent(rememberMeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(forgotPasswordLbl))
                    .addComponent(loginErrorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(144, 144, 144))
        );

        rightPnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {logInBtn, passwordTxtFld, usernameTxtFld});

        rightPnlLayout.setVerticalGroup(
            rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPnlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(rightPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forgotPasswordLbl)
                    .addComponent(rememberMeCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        rightPnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logInBtn, passwordTxtFld, usernameTxtFld});

        loginPanel.add(rightPnl);
        rightPnl.setBounds(720, 0, 730, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFldActionPerformed
    private void initializeLayout() {
        
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loginPanel,"LoginScreen");
        getContentPane().add(mainPanel, "MainScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadingScreen");
    }
    public void loadProductInitialData(){
       inventoryMS Product1=new inventoryMS(1,"Samsung",43,54500,"HD",true,5);
        inventoryMS Product2=new inventoryMS(2,"LG",55,70500,"UHD",true,2);
        inventoryMS Product3=new inventoryMS(3,"TCL",24,19000,"HD",false,4);
        inventoryMS Product4=new inventoryMS(4,"Samsung",55,69000,"UHD",true,1);
        inventoryMS Product5=new inventoryMS(5,"TCL",32,30000,"UHD",true,3);
        productList.add(Product1);
        productList.add(Product2);
        productList.add(Product3);
        productList.add(Product4);
        productList.add(Product5);
        loadProductListToTable();
    }
    
    private void loadProductListToTable(){
        DefaultTableModel model = (DefaultTableModel) inventoryTbl.getModel();
        
        //Clear existing rows
        model.setRowCount(0);
        
        //Add rows from prodcutList
        for (inventoryMS product : productList){
            model.addRow(new Object[] {
                product.getModelNo(),
                product.getCompany(),
                product.getSize(),
                product.getPrice(),
                product.getResolution(),
                product.isSmart(),
                product.getInStock()
            });
        }
    }
    
    
    private void loadSortedProductListToTable(List<inventoryMS> sortedList){
        DefaultTableModel model = (DefaultTableModel) inventoryTbl.getModel();
        
        //Clear existing rows
        model.setRowCount(0);
        
        //Add rows from prodcutList
        for (inventoryMS product : sortedList){
            model.addRow(new Object[] {
                product.getModelNo(),
                product.getCompany(),
                product.getSize(),
                product.getPrice(),
                product.getResolution(),
                product.isSmart(),
                product.getInStock()
            });
        }
    }
    
    
    private void addProduct(inventoryMS product) {
        productList.add(product);
        loadProductListToTable();
    }
    
    private boolean deleteProduct(int modelNo){
    for (inventoryMS product:productList){
        if(product.getModelNo()==modelNo){
            productList.remove(product);
            loadProductListToTable();
            return true;
        }

    }
    loadProductListToTable();
     return false;

    }
    
    private Boolean updateProduct(inventoryMS product){
        int modelNo=product.getModelNo();
        boolean flag=false;
        for (inventoryMS productUpdate:productList){
          if(modelNo==productUpdate.getModelNo()){
             productUpdate.setCompany(product.getCompany());
             productUpdate.setSize(product.getSize());
             productUpdate.setPrice(product.getPrice());
             productUpdate.setResolution(product.getResolution());
             productUpdate.setInStock(product.getInStock());
             productUpdate.setSmart(product.isSmart());
             loadProductListToTable();
              return true;
             }
        }
       
    loadProductListToTable();
     return false;

}
    private boolean addProduct() {
         int modelNo = Integer.parseInt(modelNoTxtFld.getText());
            String company = companyTxtFld.getText();
            int size = Integer.parseInt(sizeTxtFld.getText());
            int price = Integer.parseInt(priceTxtFld.getText());
            String resolution =resolutionTxtFld.getText();
            int inStock = Integer.parseInt(inStockTxtFld.getText());
            boolean smart = smartCheckBox.isSelected();
        
            if( companyTxtFld.getText().trim().isEmpty() ||
                resolutionTxtFld.getText().trim().isEmpty() ||
                    Integer.parseInt(modelNoTxtFld.getText().trim())==0||
                    Integer.parseInt(priceTxtFld.getText().trim())==0||
                    Integer.parseInt(inStockTxtFld.getText().trim())==0||
                    Integer.parseInt(sizeTxtFld.getText().trim())==0)
        {
            JOptionPane.showMessageDialog(this,"Please Fill All the Values","Not Sucessful",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else {
            for (inventoryMS ModelNo:productList){
                if (modelNo==ModelNo.getModelNo()){
                    JOptionPane.showMessageDialog(this, "Product of this model no already exists!","Alert",JOptionPane.WARNING_MESSAGE);
                   return false;
                }
            }    
                
            inventoryMS product= new inventoryMS( modelNo,company,size,price,resolution,smart,inStock);
            productList.add(product);
            loadProductListToTable();
            JOptionPane.showMessageDialog(this,"Product Added Successfully!!","Successful",JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
    }
    
    private void loadScreen(String screenName) {
       cardLayout.show(getContentPane(), screenName);
    }
    
    private void clearFields(){
        modelNoTxtFld.setText("");
        sizeTxtFld.setText("");
        priceTxtFld.setText("");
        resolutionTxtFld.setText("");
        inStockTxtFld.setText("");
        companyTxtFld.setText("");
        smartCheckBox.setSelected(false);
        
    }
    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        String username = usernameTxtFld.getText();
        String password = new String(passwordTxtFld.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            loginErrorLbl.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            loginErrorLbl.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            loginErrorLbl.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_logInBtnActionPerformed

    private void rememberMeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberMeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberMeCheckBoxActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        passwordTxtFld.setText("");
        usernameTxtFld.setText("");
        loadScreen("LoginScreen");
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void sortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortComboBoxActionPerformed
        
    }//GEN-LAST:event_sortComboBoxActionPerformed

    private void inStockTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStockTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStockTxtFldActionPerformed

    private void companyTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTxtFldActionPerformed

    private void sizeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeTxtFldActionPerformed

    private void modelNoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNoTxtFldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try{int modelNo=Integer.parseInt(modelNoTxtFld.getText());
            String company=companyTxtFld.getText();
            int size=Integer.parseInt(sizeTxtFld.getText());
            int price=Integer.parseInt(priceTxtFld.getText());
            String resolution=resolutionTxtFld.getText();
            int inStock=Integer.parseInt(inStockTxtFld.getText());
            Boolean smart=smartCheckBox.isSelected();
            
            
           if (modelNoTxtFld.getText().isEmpty()||companyTxtFld.getText().isEmpty()||sizeTxtFld.getText().isEmpty()||priceTxtFld.getText().isEmpty()||resolutionTxtFld.getText().isEmpty()||inStockTxtFld.getText().isEmpty()){
           JOptionPane.showMessageDialog(this,"Please Fill All The Fields,Product Not Added!!","Error",JOptionPane.ERROR_MESSAGE);
           }
           else{
           inventoryMS updatedProduct=new inventoryMS(modelNo,  company,  size,  price,  resolution, smart,inStock);
              boolean flag=updateProduct(updatedProduct);
               if (flag==false){
                    JOptionPane.showMessageDialog(this,"Product with that Model No not found in the list.", "Product Not Found", JOptionPane.WARNING_MESSAGE);
               }
               else{
                   JOptionPane.showMessageDialog(this,"Product Details Updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
               }
               }}
                catch (Exception e) {
               // Handle any other unexpected exceptions
               JOptionPane.showMessageDialog(this, "An error occurred while updating the details.", "Error", JOptionPane.ERROR_MESSAGE);
                // Optionally print the stack trace for debugging
           }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
           addProduct();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "An error occurred while adding the details.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try{int modelNo=Integer.parseInt(modelNoTxtFld.getText());
        if(deleteProduct(modelNo)==true){

            JOptionPane.showMessageDialog(this,"Product Deleted Successfully!!","Successful",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"Product of this Model No is not in the table.","Product Not Found!",JOptionPane.WARNING_MESSAGE);
        } 
        }
        catch (NumberFormatException e) {
        
        JOptionPane.showMessageDialog(this, "Invalid Product ID. Please enter a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Catch any other unexpected exceptions
        JOptionPane.showMessageDialog(this, "An error occurred while deleting the product.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void forgotPasswordLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLblMouseClicked
        JOptionPane.showMessageDialog(this, "Oops! For this you may have to contact the developers.", "Forgot Password", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_forgotPasswordLblMouseClicked

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        int selectedIndex = sortComboBox.getSelectedIndex();
        if (selectedIndex == 0) {
            selectionSort sorter = new selectionSort();
            List<inventoryMS> productSortedList = sorter.sortByModelNo(productList, false);
            loadSortedProductListToTable(productSortedList);
        }
        else if (selectedIndex == 1) {
            insertionSort sorter = new insertionSort();
            List<inventoryMS> productSortedList = sorter.sortBySize(productList, false);
            loadSortedProductListToTable(productSortedList);
        }
        else if (selectedIndex==2){
            mergeSort sorter = new mergeSort();
            List<inventoryMS> productSortedList = sorter.sortByPrice(productList, false);
            loadSortedProductListToTable(productSortedList);
        }
        else if (selectedIndex==3){
            selectionSortCompany sorter = new selectionSortCompany();
            List<inventoryMS> productSortedList = sorter.sortByCompany(productList, false);
            loadSortedProductListToTable(productSortedList);
        }
        
        
    }//GEN-LAST:event_sortButtonActionPerformed

    private void refershButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refershButtonActionPerformed
        loadSortedProductListToTable(productList);
           
    }//GEN-LAST:event_refershButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        selectionSortCompany SortedList = new selectionSortCompany();
        List<inventoryMS> productSortedList = SortedList.sortByCompany(productList, false);
        binarySearch search = new binarySearch();
        inventoryMS data = search.searchByCompany(searchTxtField.getText().trim(),productSortedList, 0, productSortedList.size()-1);
        if (data!=null){
            JOptionPane.showMessageDialog(this, "Found","Found",JOptionPane.INFORMATION_MESSAGE);
            List<inventoryMS> tempoList=new ArrayList<>();
            tempoList.add(data);
            loadSortedProductListToTable(tempoList);
        }
        else{
            JOptionPane.showMessageDialog(this, "Data not Found","Not Found",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTabbedPane bodyPnl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel companyNameLbl;
    private javax.swing.JLabel companySloganLbl;
    private javax.swing.JTextField companyTxtFld;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel forgotPasswordLbl;
    private javax.swing.JLabel headerCompanyName;
    private javax.swing.JLabel headerCompanySlogan;
    private javax.swing.JLabel headerLogo;
    private javax.swing.JPanel headerPnl;
    private javax.swing.JLabel helpLbl;
    private javax.swing.JTextField helpTxtFld;
    private javax.swing.JPanel homePnl;
    private javax.swing.JLabel homeWlcMsgLbl;
    private javax.swing.JTextField inStockTxtFld;
    private javax.swing.JPanel inventoryStockPnl;
    private javax.swing.JScrollPane inventoryTableScrollPnl;
    private javax.swing.JTable inventoryTbl;
    private javax.swing.JPanel leftPnl;
    private javax.swing.JButton logInBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel loginErrorLbl;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel manageInventoryPnl;
    private javax.swing.JLabel mgmtLbl;
    private javax.swing.JTextField modelNoTxtFld;
    private javax.swing.JPasswordField passwordTxtFld;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JButton refershButton;
    private javax.swing.JCheckBox rememberMeCheckBox;
    private javax.swing.JTextField resolutionTxtFld;
    private javax.swing.JPanel rightPnl;
    private javax.swing.JButton searchButton1;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTextField sizeTxtFld;
    private javax.swing.JCheckBox smartCheckBox;
    private javax.swing.JButton sortButton;
    private javax.swing.JComboBox<String> sortComboBox;
    private javax.swing.JLabel sortLbl;
    private javax.swing.JPanel supportPnl;
    private javax.swing.JLabel tvLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JScrollPane userGuideScrollPnl;
    private javax.swing.JLabel userGuideTitleLbl;
    private javax.swing.JTextArea userGuideTxtArea;
    private javax.swing.JTextField usernameTxtFld;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
